---
- name: Deploy LEMP stack with WordPress and SFTP
  hosts: localhost
  tasks:
    - name: Download and Install MySQL repository
      yum:
        name: https://repo.mysql.com/mysql84-community-release-el9-1.noarch.rpm
        state: present
        disable_gpg_check: yes

    - name: Install MySQL server and PHP extensions
      yum:
        name:
          - mysql-community-server
          - python3-pip
          - php
          - php-fpm
          - php-mysqlnd
          - php-cli
          - php-common
          - php-json
          - php-opcache
          - php-mbstring
          - php-xml
          - php-curl
          - nginx
        state: present

    - name: Install MySQL Python dependency
      pip:
        name: PyMySQL
        executable: pip3

    - name: Enable and start services
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - mysqld
        - php-fpm
        - nginx

    - name: Ensure the 'project' group exists
      ansible.builtin.group:
        name: project
        state: present

    - name: Create project user and group
      user:
        name: project
        password: "{{ 'project' | password_hash('sha512') }}"
        groups: [ sftpusers, nginx ]
        append: yes

    - name: Create project directory structure
      file:
        path: /home/project/project/public
        state: directory
        owner: project
        group: project
        mode: '0755'
        recurse: yes

    - name: Set SELinux permissions
      seboolean:
        name: httpd_enable_homedirs
        state: yes
        persistent: yes

    - name: Configure Nginx for WordPress
      copy:
        dest: /etc/nginx/conf.d/project.conf
        content: |
          server {
            listen 80;
            server_name adnan.adnansal.im;

            root /home/project/project/public;
            index index.php index.html;

            location / {
                try_files $uri $uri/ /index.php?$query_string;
            }

            location ~ \.php$ {
                include fastcgi_params;
                fastcgi_pass unix:/run/php-fpm/www.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            }

            location ~ /\.ht {
                deny all;
            }
          }

    - name: Configure SFTP access
      copy:
        dest: /etc/ssh/sshd_config.d/sftp.conf
        content: |
          Match Group sftpusers
              ChrootDirectory %h
              ForceCommand internal-sftp
              AllowTcpForwarding no
              X11Forwarding no
              PasswordAuthentication yes

    - name: Restart SSH service
      systemd:
        name: sshd
        state: restarted

    - name: Set SFTP directory permissions
      file:
        path: /home/project
        state: directory
        owner: root
        group: sftpusers
        mode: '0755'

    - name: Set project public directory permissions
      file:
        path: /home/project/project/public
        state: directory
        owner: project
        group: sftpusers
        mode: '0755'

    - name: Download and extract phpMyAdmin
      unarchive:
        src: https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.tar.gz
        dest: /home/project/project/public/
        remote_src: yes
        creates: /home/project/project/public/phpmyadmin

    - name: Rename phpMyAdmin folder
      shell: >
        mv /home/project/project/public/phpMyAdmin-* /home/project/project/public/phpmyadmin
      args:
        creates: /home/project/project/public/phpmyadmin

    - name: Configure Nginx for phpMyAdmin
      copy:
        dest: /etc/nginx/conf.d/phpmyadmin.conf
        content: |
          server {
            listen 80;
            server_name adnan.adnansal.im;

            location /phpmyadmin {
                root /home/project/project/public;
                index index.php;
                try_files $uri $uri/ /index.php;
            }

            location ~ ^/phpmyadmin/(.+\.php)$ {
                root /home/project/project/public;
                fastcgi_pass unix:/run/php-fpm/www.sock;
                fastcgi_index index.php;
                include fastcgi.conf;
            }
          }

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted

    - name: Download and extract WordPress
      shell: >
        cd /home/project/project/public/ &&
        wget https://wordpress.org/latest.tar.gz &&
        tar -xzf latest.tar.gz &&
        mv wordpress/* . &&
        rm -rf wordpress latest.tar.gz wp-config-sample.php
      args:
        creates: /home/project/project/public/index.php

    - name: Set WordPress file permissions
      file:
        path: /home/project/project/public
        state: directory
        owner: project
        group: project
        mode: '0755'
        recurse: yes

    - name: Configure MySQL
      copy:
        dest: /etc/my.cnf
        content: |
          [mysqld]
          mysql_native_password=ON
          datadir=/var/lib/mysql
          socket=/var/lib/mysql/mysql.sock
          log-error=/var/log/mysqld.log
          pid-file=/var/run/mysqld/mysqld.pid

    - name: Restart MySQL
      service:
        name: mysqld
        state: restarted

    - name: Get MySQL temporary root password
      shell: "grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'"
      register: mysql_temp_password
      changed_when: false

    - name: Update MySQL root password
      shell: >
        mysqladmin --user=root --password="{{ mysql_temp_password.stdout }}"
        password "Ansible#1"
      ignore_errors: yes

    - name: Configure MySQL database and user
      community.mysql.mysql_db:
        login_user: root
        login_password: "Ansible#1"
        name: wordpress
        state: present

    - name: Create WordPress MySQL user
      community.mysql.mysql_user:
        login_user: root
        login_password: "Ansible#1"
        name: wpuser
        password: "WPUser#1"
        priv: 'wordpress.*:ALL'
        host: localhost
        state: present

    - name: Fetch WordPress salts
      command: curl https://api.wordpress.org/secret-key/1.1/salt/
      register: "wp_salt"

    - name: Generate wp-config.php
      copy:
        dest: /home/project/project/public/wp-config.php
        content: |
          <?php
          define( 'DB_NAME', 'wordpress' );
          define( 'DB_USER', 'wpuser' );
          define( 'DB_PASSWORD', 'WPUser#1' );
          define( 'DB_HOST', 'localhost' );
          define( 'DB_CHARSET', 'utf8mb4' );
          define( 'DB_COLLATE', '' );

          {{ wp_salt.stdout }}

          $table_prefix = 'wp_';
          define( 'WP_DEBUG', false );

          if ( ! defined( 'ABSPATH' ) ) {
              define( 'ABSPATH', __DIR__ . '/' );
          }
          require_once ABSPATH . 'wp-settings.php';
        owner: project
        group: project

    - name: Reload and restart services
      systemd:
        name: "{{ item }}"
        state: restarted
      loop:
        - nginx
        - php-fpm
        - mysqld

